spring:
  application:
    name: rabbit-feign-consumer

server:
    port: 8770

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8750/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

logging:
  level:
    com.rabbit.practise.apigateway.consumer.RefactorHelloService: DEBUG