/*
 * File: ConditionalImpl.java
 *
 * $Id: ConditionalImpl.java,v 1.8 2000/11/20 01:51:04 bokowski Exp $
 *
 * This file is part of Barat.
 * Copyright (c) 1998-2000 Boris Bokowski (bokowski@users.sourceforge.net)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of Boris Bokowski nor the names of his contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL BORIS BOKOWSKI
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package barat.parser;

/* generated by Boris Bokowski's rosegen on Sat Jul 11 18:34:51 GMT+03:30 1998
*/

import barat.reflect.Conditional;
import barat.reflect.AExpression;


public class ConditionalImpl extends AExpressionImpl implements Conditional
{
	private Attribute<AExpression> condition;
	private Attribute<AExpression> ifTrue;
	private Attribute<AExpression> ifFalse;
	public ConditionalImpl( Attribute<AExpression> condition_, Attribute<AExpression> ifTrue_, Attribute<AExpression> ifFalse_)
	{
		super( );
		condition = condition_;
		if(condition!=null)
			condition.setupContainment(this, "condition");
		ifTrue = ifTrue_;
		if(ifTrue!=null)
			ifTrue.setupContainment(this, "ifTrue");
		ifFalse = ifFalse_;
		if(ifFalse!=null)
			ifFalse.setupContainment(this, "ifFalse");
	}
	public ConditionalImpl() {}
	public void setCondition( Attribute<AExpression> condition_ )
	{
		condition = condition_;
		condition.setupContainment(this, "condition");
	}
	public AExpression getCondition()
	{
		return condition.value();
	}
	public void setIfTrue( Attribute<AExpression> ifTrue_ )
	{
		ifTrue = ifTrue_;
		ifTrue.setupContainment(this, "ifTrue");
	}
	public AExpression getIfTrue()
	{
		return ifTrue.value();
	}
	public void setIfFalse( Attribute<AExpression> ifFalse_ )
	{
		ifFalse = ifFalse_;
		ifFalse.setupContainment(this, "ifFalse");
	}
	public AExpression getIfFalse()
	{
		return ifFalse.value();
	}
	public void accept(barat.Visitor v)
	{
		v.visitConditional(this);
	}
	public void accept(barat.parser.ImplementationVisitor v)
	{
		v.visitConditionalImpl(this);
	}
}
