spring:
  application:
    name: rabbit-eureka-server

server:
  port: 8751

eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://peer2:8752/eureka/