#!/bin/sh

# Call this with a type name as argument; it creates a generic instantiation
# of the collections for that type.

# $Id: instantiate,v 1.3 1999/02/06 15:58:53 spiegel Exp $

PACKAGE=java.lang

if [ -f ../reflect/$2.java ] ; then
    PACKAGE=barat.reflect ;
elif [ -f ../$2.java ] ; then
    PACKAGE=barat ;
elif [ $2 = Suspension ] ; then
    PACKAGE=barat.codegen ;
fi

cat $1.generic | sed -e 's/\$TYPE\$/'$2'/g;s/\$PACKAGE\$/'$PACKAGE'/g' > $2$1.java
