package com.xiaoqq.practise.cglib.learn1;

import net.sf.cglib.proxy.Callback;
import net.sf.cglib.proxy.Factory;
import net.sf.cglib.proxy.FixedValue;

/**
 * This class shows the class content generated by Cglib for class "SampleClass".
 */
public class SampleClass$$EnhancerByCGLIB$$aa910451 extends SampleClass implements Factory
{
    private boolean CGLIB$BOUND;
    private static ThreadLocal CGLIB$THREAD_CALLBACKS;
    private static Callback[] CGLIB$STATIC_CALLBACKS;
    private FixedValue CGLIB$CALLBACK_0;

    static void CGLIB$STATICHOOK1()
    {
        CGLIB$THREAD_CALLBACKS = new ThreadLocal();
        return;
    }

    public final String test(String paramString)
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }
        try {
            return (String)this.CGLIB$CALLBACK_0.loadObject();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    protected final void finalize()
            throws Throwable
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }
    }

    public final boolean equals(Object paramObject)
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }

        Object tmp22_17 = null;
        try {
            tmp22_17 = this.CGLIB$CALLBACK_0.loadObject();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return tmp22_17 == null ? false : ((Boolean)tmp22_17).booleanValue();
    }

    public final String toString()
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }
        try {
            return (String)this.CGLIB$CALLBACK_0.loadObject();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public final int hashCode()
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }

        Object tmp22_17 = null;
        try {
            tmp22_17 = this.CGLIB$CALLBACK_0.loadObject();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return tmp22_17 == null ? 0 : ((Number)tmp22_17).intValue();
    }

    protected final Object clone()
            throws CloneNotSupportedException
    {
        FixedValue tmp4_1 = this.CGLIB$CALLBACK_0;
        if (tmp4_1 == null)
        {
            CGLIB$BIND_CALLBACKS(this);
        }
        try {
            return this.CGLIB$CALLBACK_0.loadObject();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public SampleClass$$EnhancerByCGLIB$$aa910451()
    {
        CGLIB$BIND_CALLBACKS(this);
    }

    public static void CGLIB$SET_THREAD_CALLBACKS(Callback[] paramArrayOfCallback)
    {
        CGLIB$THREAD_CALLBACKS.set(paramArrayOfCallback);
    }

    public static void CGLIB$SET_STATIC_CALLBACKS(Callback[] paramArrayOfCallback)
    {
        CGLIB$STATIC_CALLBACKS = paramArrayOfCallback;
    }

    private static final void CGLIB$BIND_CALLBACKS(Object paramObject)
    {
        SampleClass$$EnhancerByCGLIB$$aa910451 localaa910451 = (SampleClass$$EnhancerByCGLIB$$aa910451)paramObject;
        if (!localaa910451.CGLIB$BOUND)
        {
            localaa910451.CGLIB$BOUND = true;
            Object tmp23_20 = CGLIB$THREAD_CALLBACKS.get();
            if (tmp23_20 == null)
            {
                return ;
            }
            localaa910451.CGLIB$CALLBACK_0 = (FixedValue) tmp23_20;
        }
        return;
    }

    @Override
    public Object newInstance(Callback[] callbacks) {
        CGLIB$SET_THREAD_CALLBACKS(callbacks);
        SampleClass$$EnhancerByCGLIB$$aa910451 proxy = new SampleClass$$EnhancerByCGLIB$$aa910451();
        CGLIB$SET_THREAD_CALLBACKS(null);
        return proxy;
    }

    @Override
    public Object newInstance(Callback callback) {
        Callback[] callbacks = new Callback[]{};
        callbacks[0] = callback;
        CGLIB$SET_THREAD_CALLBACKS(callbacks);
        SampleClass$$EnhancerByCGLIB$$aa910451 proxy = new SampleClass$$EnhancerByCGLIB$$aa910451();
        CGLIB$SET_THREAD_CALLBACKS(null);
        return proxy;
    }

    @Override
    public Object newInstance(Class[] clazzes, Object[] objects, Callback[] callbacks) {
        CGLIB$SET_THREAD_CALLBACKS(callbacks);
        SampleClass$$EnhancerByCGLIB$$aa910451 proxy;
        for (Class clazz: clazzes) {
            proxy = new SampleClass$$EnhancerByCGLIB$$aa910451();
            CGLIB$SET_THREAD_CALLBACKS(null);
            return proxy;
        }
        return null;
    }

    @Override
    public Callback getCallback(int index) {
        CGLIB$BIND_CALLBACKS(this);
        return CGLIB$CALLBACK_0;
    }

    @Override
    public Callback[] getCallbacks() {
        CGLIB$BIND_CALLBACKS(this);
        Callback[] callbacks = new Callback[]{};
        callbacks[0] = CGLIB$CALLBACK_0;
        return callbacks;
    }

    @Override
    public void setCallback(int index, Callback callback) {
        CGLIB$CALLBACK_0 = (FixedValue) callback;
    }

    @Override
    public void setCallbacks(Callback[] callbacks) {
        CGLIB$CALLBACK_0 = (FixedValue) callbacks[0];
    }
}
